# Generated by Django 3.0.7 on 2020-07-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0002_auto_20200710_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Posts.Post')),
            ],
        ),
    ]
