# Generated by Django 3.0.7 on 2020-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0003_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
